package marc.scp.scp;

/**
 * Created by Marc on 5/1/14.
 */
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable
//object persisting in database
public class Preferences
{
    //table fields
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    private int id;
    @DatabaseField(index = true)
    String hostname;
    @DatabaseField
    String username;
    @DatabaseField
    String  password;
    @DatabaseField
    String  rsaKey;
    @DatabaseField
    int port;

    Preferences()
    {
        // needed by ormlite
    }

    public Preferences(String h, String u, String pass, int p)
    {
        hostname = h;
        username = u;
        port = p;
        password = pass;
    }
}
